### PR TITLE
Complete SendThread.java (server) and RecvThread.java (client), but i…

### PR DESCRIPTION
**Pull request by ipolyak**
…t not tested :(

### CODE REVIEW

**Comment by andreymarchenko** [comment]
Chto zamergil?

**Comment by ipolyak** [comment]
Zamerzil opredelenno chto-to ne choroshee!

**Comment by andreymarchenko** [comment]
Ya poehal domoi, koroche, nado posmotret' chto ti sdelal

**Comment by ipolyak** [comment]
Tam vse zaebis'!!

**Pull request merged**
